### ISSUE TITLE
StreamSystem QuerySequence times out

### ISSUE THREAD

**Issue by johanneshall** [rabbitmq/rabbitmq-stream-dotnet-client#131]
When trying to read the publishing id using QuerySequence it throws a TimeoutException about 8-9 times out of 10. The stream exists and has 2002 messages.
The setup is a 3 node cluster behind a load balancer. The load balancer used is Traefik with round robin between the nodes.

Using the java library and similar code works.

The rabbitmq nodes shows an error in the logs when this happens. This is included as rabbitmq_log.txt in zip file at the bottom.

The code used for testing:

c#:
```
using RabbitMQ.Stream.Client;
using System.Net;

namespace RabbitMQTest2
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            const string stream = "stream";
            AddressResolver addressResolver = new AddressResolver(new IPEndPoint(IPAddress.Parse("x.x.x.x"), 5552)); //192.168.22.10 10.2.1.189
            StreamSystemConfig config = new StreamSystemConfig
            {
                UserName = "user",
                Password = "password",
                VirtualHost = "dev",
                AddressResolver = addressResolver,
                Endpoints = new List<EndPoint> { addressResolver.EndPoint }
            };

            do
            {
                var system = await StreamSystem.Create(config);

                try
                {
                    var result = await system.QuerySequence("producer", stream);
                    Console.WriteLine($"{DateTime.Now} :  Got result: {result}");
                    await Task.Delay(1000);
                }
                catch (Exception e)
                {
                    Console.WriteLine($"{DateTime.Now} :  Failed: {e.Message}");
                }

                await system.Close();

            } while (true);
        }
    }
}
```
c# output:
```
2022-06-01 12:51:29 :  Failed: The operation has timed out.
2022-06-01 12:51:39 :  Failed: The operation has timed out.
2022-06-01 12:51:39 :  Got result: 2002
2022-06-01 12:51:50 :  Failed: The operation has timed out.
2022-06-01 12:52:00 :  Failed: The operation has timed out.
2022-06-01 12:52:10 :  Failed: The operation has timed out.
2022-06-01 12:52:20 :  Failed: The operation has timed out.
2022-06-01 12:52:30 :  Failed: The operation has timed out.
2022-06-01 12:52:40 :  Failed: The operation has timed out.
2022-06-01 12:52:51 :  Failed: The operation has timed out.
2022-06-01 12:52:51 :  Got result: 2002
2022-06-01 12:53:02 :  Failed: The operation has timed out.
2022-06-01 12:53:12 :  Failed: The operation has timed out.
2022-06-01 12:53:22 :  Failed: The operation has timed out.
2022-06-01 12:53:32 :  Failed: The operation has timed out.
2022-06-01 12:53:42 :  Failed: The operation has timed out.
2022-06-01 12:53:52 :  Failed: The operation has timed out.
2022-06-01 12:53:52 :  Got result: 2002
2022-06-01 12:54:03 :  Failed: The operation has timed out.
2022-06-01 12:54:13 :  Failed: The operation has timed out.
2022-06-01 12:54:23 :  Failed: The operation has timed out.
2022-06-01 12:54:33 :  Failed: The operation has timed out.
2022-06-01 12:54:43 :  Failed: The operation has timed out.
2022-06-01 12:54:53 :  Failed: The operation has timed out.
```

java:
```
package org.example;

import com.rabbitmq.stream.*;
import java.time.LocalDateTime;

public class Main {
    public static void main(String[] args) {

        String stream =  "stream";
        Address entryPoint = new Address("x.x.x.x", 5552);

        do {
            Environment environment = Environment.builder()
                    .host(entryPoint.host())
                    .port(entryPoint.port())
                    .addressResolver(address -> entryPoint)
                    .username("user")
                    .password("password")
                    .virtualHost("dev")
                    .build();

            Producer producer = environment.producerBuilder()
                    .stream(stream)
                    .name("producer")
                    .build();

            try {
                long id = producer.getLastPublishingId();
                System.out.printf(LocalDateTime.now().toString() + " : Got result: " + id + "\r\n");
                Thread.sleep(1000);

            } catch (Exception e) {
                System.out.printf(LocalDateTime.now().toString() + " : Failed: " + e.getMessage()+ "\r\n");
            }

            producer.close();
            environment.close();

        } while (true);
    }
}
```
java output:
```
2022-06-01T12:54:11.462489300 : Got result: 2002
2022-06-01T12:54:18.796583300 : Got result: 2002
2022-06-01T12:54:22.048833200 : Got result: 2002
2022-06-01T12:54:29.417930400 : Got result: 2002
2022-06-01T12:54:32.666894100 : Got result: 2002
2022-06-01T12:54:39.979889900 : Got result: 2002
2022-06-01T12:54:43.205883600 : Got result: 2002
2022-06-01T12:54:50.505902800 : Got result: 2002
2022-06-01T12:54:58.855058100 : Got result: 2002
2022-06-01T12:55:02.089557500 : Got result: 2002
2022-06-01T12:55:09.408048800 : Got result: 2002
2022-06-01T12:55:12.642313900 : Got result: 2002
2022-06-01T12:55:19.972241900 : Got result: 2002
2022-06-01T12:55:23.198732200 : Got result: 2002
2022-06-01T12:55:31.541814400 : Got result: 2002
2022-06-01T12:55:34.779194200 : Got result: 2002
```
Stacktrace:
```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.ThrowForFailedGetResult(Int16 token)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at RabbitMQ.Stream.Client.ManualResetValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource<T>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at RabbitMQ.Stream.Client.Client.<Request>d__47`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at RabbitMQ.Stream.Client.Client.<Request>d__47`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at RabbitMQ.Stream.Client.Client.<QueryPublisherSequence>d__55.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at RabbitMQ.Stream.Client.StreamSystem.<QuerySequence>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RabbitMQTest2.Program.<Main>d__0.MoveNext() in D:\code\vs\RabbitMQTest2\Program.cs:line 28
```
[querysequence.zip](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/files/8813522/querysequence.zip)

**Comment by Gsantomaggio** [comment]
Java works because the producer is already connected to the leader node.

```java
long id = producer.getLastPublishingId();
```

it is just a different approach. 
In this client the Query calls are on the System Level
```csharp
    system.QueryOffset()
    system.QuerySequence()
```

**Comment by johanneshall** [comment]
This issue is no longer present in latest version of rabbitmq.
