### ISSUE TITLE
Incorrect endpoint for reconnection

### ISSUE THREAD

**Issue by ricsiLT** [rabbitmq/rabbitmq-stream-dotnet-client#133]
Hi,

Reporting an issue which hits us sometimes.

## Setup

* RabbitMQ 3.9.12
* Erlang 23.3.4.11
* Reliable Producer
* Heartbeat enabled, 30s
* Using load balancer

## Issue

Sometimes, we will see the following sequence in the logs after we successfully create `StreamSystem`, during creation of `ReliableProducer`:

```
INFO: Producer reference: ENV-PRODUCT-GUID,stream: STREAM_NAME  is disconnected. Client will try reconnect

ERROR: Error during initialization: System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at RabbitMQ.Stream.Client.Connection.Create(EndPoint endpoint, Func`2 commandCallback, Func`2 closedCallBack, SslOption sslOption)
   at RabbitMQ.Stream.Client.Client.Create(ClientParameters parameters)
   at RabbitMQ.Stream.Client.StreamSystem.MayBeReconnectLocator()
   at RabbitMQ.Stream.Client.StreamSystem.CreateProducer(ProducerConfig producerConfig)
   at RabbitMQ.Stream.Client.Reliable.ReliableProducer.GetNewReliable(Boolean boot)
 ---> System.Net.Sockets.SocketException Data:
    Address : 127.0.0.1
    Port : 5552
```

We think `MayBeReconnectLocator()` is using incorrect `ClientParamaters` and should instead use `_client.Parameters` but didn't have enough time to properly step through it. As I don't see any other way it would try to connect to localhost:5552 apart from using default instance of `ClientParameters`?

**Comment by Gsantomaggio** [comment]
Thanks for reporting @ricsiLT 
I will investigate I think you are right

**Comment by ricsiLT** [comment]
Which part of the error is important here? Kinda difficult to search for them in our logging setup. Can I focus on a single line? I do see some `exception exit: {{function_clause,` with our stream name beneath.

**Comment by Gsantomaggio** [comment]
@ricsiLT don't worry. 

The problem was that the ReiableProducer used `system.QuerySequence("reference", "my_stream")` to get the last id.

In some case, you could have this kind of the problem: https://github.com/rabbitmq/rabbitmq-server/pull/4898

Whit this [commit](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/134/commits/be63005c8cb745d8406e8055abbb9b177736d9e3). You don't have this kind of the problem anymore since the  `ReiableProducer` uses `producer.GetLastPublishingId()`.

`producer.GetLastPublishingId()` uses the right connection to get the lastid.


So if the  PR https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/134 is ok with you we can merge
