### ISSUE TITLE
SuperStream SingleActiveConsumer exception - StreamDoesNotExist

### ISSUE THREAD

**Issue by rossbuggins** [rabbitmq/rabbitmq-stream-dotnet-client#195]
Hi, I'm trying out superstreams/single active consumer. I've got the below code, but get exception when producer is created saying stream does not exist. Looking at rabbitmq console output, its saying it cant find exchange matching the stream name (a queue does exist though). I think I'm probably just missing something, but not sure what. Using version 1.0.0-rc.8 and rabbitmq docker rabbitmq:3.11.4-management-alpine. Streams without the SuperStreamConfig are working ok. thanks, Ross

dotnet exception:
```
Exception has occurred: CLR/RabbitMQ.Stream.Client.CreateProducerException
An exception of type 'RabbitMQ.Stream.Client.CreateProducerException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'producer could not be created code: StreamDoesNotExist'
   at RabbitMQ.Stream.Client.StreamSystem.<CreateRawSuperStreamProducer>d__10.MoveNext()
   at RabbitMQ.Stream.Client.Reliable.ProducerFactory.<SuperStreamProducer>d__3.MoveNext()
   at RabbitMQ.Stream.Client.Reliable.ProducerFactory.<CreateProducer>d__2.MoveNext()
   at RabbitMQ.Stream.Client.Reliable.Producer.<CreateNewEntity>d__4.MoveNext()
   at RabbitMQ.Stream.Client.Reliable.ReliableBase.<Init>d__4.MoveNext()
   at RabbitMQ.Stream.Client.Reliable.ReliableBase.<Init>d__3.MoveNext()
   at RabbitMQ.Stream.Client.Reliable.Producer.<Create>d__3.MoveNext()
   at Program.<<<Main>$>g__Start|0_0>d.MoveNext() in /home/rb/source/account/superstreams/Program.cs:line 53
   at Program.<<Main>$>d__0.MoveNext() in /home/rb/source/account/superstreams/Program.cs:line 16
```

rabbitmq output:
```
account-rabbit-1  | 2022-12-14 18:25:15.178592+00:00 [error] <0.675.0> Error while looking up exchange {resource,<<"/">>,exchange,
account-rabbit-1  | 2022-12-14 18:25:15.178592+00:00 [error] <0.675.0>                                     <<"superstreamtest">>}, {amqp_error,
account-rabbit-1  | 2022-12-14 18:25:15.178592+00:00 [error] <0.675.0>                                                               not_found,
account-rabbit-1  | 2022-12-14 18:25:15.178592+00:00 [error] <0.675.0>                                                               "no exchange 'superstreamtest' in vhost '/'",
account-rabbit-1  | 2022-12-14 18:25:15.178592+00:00 [error] <0.675.0>                                                               none}

```

sample code
```
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using RabbitMQ.Stream.Client;
using RabbitMQ.Stream.Client.Reliable;
using System.Text;
using System.Buffers;
using System.Net;
using RabbitMQ.Stream.Client.AMQP;
using Performances;

Console.WriteLine("Hello, World!");

//await BatchVsBatchSend.Start();

await Start();


static async Task Start()
{
    var config = new StreamSystemConfig
    {
        UserName = "guest",
        Password = "guest",
        VirtualHost = "/"
    };

    var system = await StreamSystem.Create(config);

    const string stream = "superstreamtest";

    await system.CreateStream(new StreamSpec(stream)
    {
        MaxLengthBytes = 200000,
    });

    var exist = await system.StreamExists(stream);

    var consumer1 = await Consumer.Create(
        new ConsumerConfig(system, stream)
        {
            Reference = "my_consumer_1",
            OffsetSpec = new OffsetTypeFirst(),
            IsSingleActiveConsumer = true,
            MessageHandler = async (sourceStream, consumer, ctx, message) =>
            {
                Console.WriteLine(
                    $"message: coming from 1{sourceStream} data: {Encoding.Default.GetString(message.Data.Contents.ToArray())} - consumed");
                await Task.CompletedTask;
            }
        });

    var producer = await Producer.Create(new ProducerConfig(system, stream)
    {
       SuperStreamConfig = new SuperStreamConfig()
       {
           Routing = message1 => message1.Properties.MessageId.ToString()
       }
    }
      );

    for (var i = 0; i < 100; i++)
    {
        var message = new Message(Encoding.Default.GetBytes( $"hello{i}"))
        {
            Properties = new Properties() { MessageId = $"hello{i}" }
        };
        await producer.Send(message);
    }


    Console.WriteLine($"Press to stop");
    Console.ReadLine();

    await producer.Close();
    await consumer1.Close();
    await system.DeleteStream(stream);
    await system.Close();
}
```

**Comment by Gsantomaggio** [comment]
Hi @rossbuggins 
You need to create the super stream; please read https://www.rabbitmq.com/streams.html#super-streams 
for example:
```
rabbitmq-streams add_super_stream invoices --partitions 3
```

then use `invoices` as:
```csharp
var producer = await Producer.Create(new ProducerConfig(system,`invoices`)
    {
       SuperStreamConfig = new SuperStreamConfig()
       {
           Routing = message1 => message1.Properties.MessageId.ToString()
       }
    }
      );
```

**Comment by rossbuggins** [comment]
Thanks :-) Thought there was something I was probably missing.. I made an assumption that since a queue was appearing that the client was taking care of setup. Might be good to have an working example including superstream creation in the docs, cheers

**Comment by Gsantomaggio** [comment]
@rossbuggins I updated the documentation here: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/README.md#publish-superstream

You are right. We need a complete example with super stream and SaC. :)
Feel free to propose a PR under the directory `Example`. Else we will do! 
Thank you!

**Comment by rossbuggins** [comment]
Once I have this working I'll look at putting together a more complete example.

With the super stream created, Producer is now writing ok to the partitioned streams. The consumer is showing connected in the webgui, however, I'm not getting any messages back in the consumer's MessageHandler. Any pointers on what I should be looking for? Thanks

**Comment by Gsantomaggio** [comment]
@rossbuggins done [here](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/tree/main/Examples/SuperStream)

**Comment by RossBugginsNHS** [comment]
> @rossbuggins done [here](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/tree/main/Examples/SuperStream)

I started working on a dockerised example, at https://github.com/RossBugginsNHS/docker-rabbitmq-superstreams, but running into something with the consumers. Have moved convo go the google group https://groups.google.com/u/1/g/rabbitmq-users/c/sJZ9VRogPHM

**Comment by Gsantomaggio** [comment]
@rossbuggins thank you for the detailed repo.

Please read https://groups.google.com/g/rabbitmq-users/c/sJZ9VRogPHM
