### ISSUE TITLE
Error reading frame with large size

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-stream-dotnet-client#221]
```
Waiting for the producer to send all the messages
Sending message 0
fail: RabbitMQ.Stream.Client.Reliable.Producer[0]
      error while Process Buffer
      System.InvalidOperationException: Operation is not valid due to the current state of the object.
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at RabbitMQ.Stream.Client.Connection.Write[T](T command) in /Users/gas/git/rabbitmq/rabbitmq-stream-dotnet-client/RabbitMQ.Stream.Client/Connection.cs:line 108
         at RabbitMQ.Stream.Client.Client.Publish(Publish publishMsg) in /Users/gas/git/rabbitmq/rabbitmq-stream-dotnet-client/RabbitMQ.Stream.Client/Client.cs:line 245
         at RabbitMQ.Stream.Client.RawProducer.SendMessages(List`1 messages, Boolean clearMessagesList) in /Users/gas/git/rabbitmq/rabbitmq-stream-dotnet-client/RabbitMQ.Stream.Client/RawProducer.cs:line 217
         at RabbitMQ.Stream.Client.RawProducer.ProcessBuffer() in /Users/gas/git/rabbitmq/rabbitmq-stream-dotnet-client/RabbitMQ.Stream.Client/RawProducer.cs:line 271
```

I can reproduce the error using:
```csharp
   const int NumberOfMessages = 10_000_000;
                // Publish the messages
                for (var i = 0; i < NumberOfMessages; i++)
                {
                    var message = new Message( new byte[4 * 1024])
                    {
                    }
                    ;
```

thanks to @ricsiLT @ricardSiliuk for reporting it

**Comment by Gsantomaggio** [comment]
Full code to reproduce the issue:
```csharp
public class ProducerDrop
{
    public static async Task Start()
    {
        var loggerFactory = LoggerFactory.Create(builder =>
        {
            builder.AddSimpleConsole();
            builder.AddFilter("RabbitMQ.Stream", LogLevel.Debug);
        });

        var producerLogger = loggerFactory.CreateLogger<Producer>();
        var streamLogger = loggerFactory.CreateLogger<StreamSystem>();

       /// the server has to be in remote. In local host the problem is not raised
        var address = new AddressResolver(new IPEndPoint(IPAddress.Parse("xxxxxxx"), 5552));
        var config = new StreamSystemConfig
        {
            UserName = "test",
            Password = "test",
            AddressResolver = address,
            Endpoints = new List<EndPoint>
            {
                address.EndPoint
            }
        };
        // Connect to the broker and create the system object
        // the entry point for the client.
        var system = await StreamSystem.Create(config, streamLogger);

        const string Stream = "my_drop_stream_1";
        try
        {
            await system.DeleteStream(Stream);
        }
        catch (Exception e)
        {
            // don't care
        }

        var timeOutMessages = 0;
        var totalConf = 0;
        await system.CreateStream(new StreamSpec(Stream)
        {
            MaxLengthBytes = 15_737_418_240
        });
        var producer = await Producer.Create(
            new ProducerConfig(system, Stream)
            {
                TimeoutMessageAfter = TimeSpan.FromSeconds(5),
                // Receive the confirmation of the messages sent
                ConfirmationHandler = confirmation =>
                {
                    switch (confirmation.Status)
                    {
                        // ConfirmationStatus.Confirmed: The message was successfully sent
                        case ConfirmationStatus.Confirmed:
                            if (++totalConf % 100_000 == 0)
                            {
                                Console.WriteLine($"Confirmed message {totalConf}");
                            }
                            break;
                        case ConfirmationStatus.ClientTimeoutError:
                            timeOutMessages++;
                            if (timeOutMessages % 100 == 0)
                            {
                                Console.WriteLine($"Time out messages {timeOutMessages}");
                            }

                            break;
                        default:
                            Console.WriteLine(
                                $"Message  {confirmation.PublishingId} not confirmed. Error {confirmation.Status}");
                            break;
                    }

                    return Task.CompletedTask;
                }
            }, producerLogger);

        _ = Task.Run(async () => { await Send(producer); }
        );

        _ = Task.Run(async () => { await Send(producer); }
        );

        Console.WriteLine("Waiting for the producer to send all the messages");
        Console.ReadKey();
        Console.WriteLine("closing the producer");
        await producer.Close();
    }

    private static async Task Send(Producer p)
    {
        var start = DateTime.Now;
        const int NumberOfMessages = 50_000_000;
        const int SubBatchSize = 10;
        var sent = 0;
        var messages = new List<Message>();
        for (var i = 0; i < NumberOfMessages; i++)
        {
            var message = new Message(new byte[4 * 1024]);
            if (sent > 0 && sent % 500_000 == 0)
            {
                var elapsed = DateTime.Now - start;
                Console.WriteLine($"Sending message {i} in {elapsed.TotalSeconds} seconds");
            }

            messages.Add(message);
            if (messages.Count == SubBatchSize)
            {
                await p.Send(messages);
                sent += messages.Count;
                await p.Send(messages, CompressionType.Gzip);
                sent += messages.Count;
                messages.Clear();
            }

            await p.Send(message);
            sent++;
        }
    }
}
```


As soon you execute, you will have the following:
```csharp
fail: RabbitMQ.Stream.Client.Reliable.Producer[0]
      Error sending messages. Most likely the messages are not sent to the stream: my_drop_stream_1.Messages wont' receive confirmation so you will receive a timeout error
      System.InvalidOperationException: Operation is not valid due to the current state of the object.
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at RabbitMQ.Stream.Client.Connection.Write[T](T command) in /Users/gas/git/rabbitmq/rabbitmq-stream-dotnet-client/RabbitMQ.Stream.Client/Connection.cs:line 108
         at RabbitMQ.Stream.Client.Client.Publish(Publish publishMsg) in /Users/gas/git/rabbitmq/rabbitmq-stream-dotnet-client/RabbitMQ.Stream.Client/Client.cs:line 245
         at RabbitMQ.Stream.Client.RawProducer.SendMessages(List`1 messages, Boolean clearMessagesList) in /Users/gas/git/rabbitmq/rabbitmq-stream-dotnet-client/RabbitMQ.Stream.Client/RawProducer.cs:line 217
```
