### ISSUE TITLE
Unhandled exception. System.AggregateException: One or more errors occurred. 

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-stream-dotnet-client#25]
Found this issue working on https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/23
```stack
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.AggregateException: One or more errors occurred. (Operation is not valid due to the current state of the object.)
 ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SignalCompletion()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SetException(Exception error)
   at RabbitMQ.Stream.Client.ManualResetValueTaskSource`1.SetException(Exception error) in /source/RabbitMQ.Stream.Client/Client.cs:line 460
   at RabbitMQ.Stream.Client.Client.<>c__33`2.<Request>b__33_0(Object valueTaskSource) in /source/RabbitMQ.Stream.Client/Client.cs:line 225
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.<>c.<.cctor>b__56_0(Object obj)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
```

How to reproduce the problem:
```shell
docker run -it --rm --name test \
		-p 5552:5552 -p 5672:5672 -p 15672:15672 \
		-e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_stream advertised_host localhost" \
		-v $(pwd):/source \
		--cpuset-cpus="0-1" \
		--pull always \
		pivotalrabbitmq/rabbitmq-stream
```

Then:
```shell
docker exec -it test    /bin/bash
cd /source/
dotnet test Tests/Tests.csproj  --logger "console;verbosity=detailed"
```

Just reduce the timeout:
```csharp
private async ValueTask<TOut> Request<TIn, TOut>(Func<uint, TIn> request, int timeout = 100)
```

**Comment by Gsantomaggio** [comment]
Running the tests in a sequential with `[Collection("Sequential")]` way seems to solve the issue.

Event there are `timeout`:
```
[xUnit.net 00:00:21.14]         Got 10: 
  Failed Tests.ClientTests.ConsumerStoreOffsetShouldReceiveDelivery [10 s]
  Error Message:
   System.TimeoutException : The operation has timed out.
  Stack Trace:
     at RabbitMQ.Stream.Client.ManualResetValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource<T>.GetResult(Int16 token) in /source/RabbitMQ.Stream.Client/Client.cs:line 491

```

by the way, I am sure that there is some other hidden problem here.

**Comment by Gsantomaggio** [comment]
[Disabling the parallel tests](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/23/files#diff-eb6a4e0330bc84c8af42bb08c7d681b9a21ad3fd0cb57d61cc16015c8e1ca00cR12) seems to solve the problem

**Comment by Gsantomaggio** [comment]
Close via https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/25#issuecomment-979219852

**Comment by iuribrindeiro** [comment]
Hey @Gsantomaggio I'm still seeing this issue on my local environment. My scenario is the following:
I open 1 Stream System connection for a single consumer to be used by the whole application lifecycle (I was wondering if this is correct... Should I have more than 1 consumer? Could you direct me to some docs that answer this?)
I also open 1 Stream System connection to be used by 8 consumers.
When trying to close all of these connections I get the same error:
![image](https://user-images.githubusercontent.com/6434249/214396618-49bce536-46c3-4612-8844-f9bf26148132.png)
I tried to reproduce this in a smaller and simpler project but I couldn't :/
I bet it is realted to the fact that I'm trying to close multiple consumers and one producer at the same time.

Also, I'm starting 2 Stream Systems because if I use only 1, I can't instantiate a producer and a consumer at the same time, a deadlock happens. Also tried to reproduce this on another project but no lucky. Any thoughts?

**Comment by Gsantomaggio** [comment]
Can you give me more context ?
Ex: client versions ?
RabbitMQ versions ?

**Comment by iuribrindeiro** [comment]
yeah, sure! 
RabbitMQ 3.11.7 Erlang 25.2
RabbitMQ.Stream.Client 1.1.0

**Comment by iuribrindeiro** [comment]
Oh, and this is a super stream, btw

**Comment by Gsantomaggio** [comment]
@iuribrindeiro can you please open a discussion?
Please add a separate repo with the issue so we can easily reproduce it. Thank you

**Comment by iuribrindeiro** [comment]
> @iuribrindeiro can you please open a discussion? Please add a separate repo with the issue so we can easily reproduce it. Thank you

Done 👇 
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/discussions/222
