### ISSUE TITLE
Filters does not work with beta release

### ISSUE THREAD

**Issue by aeb-dev** [rabbitmq/rabbitmq-stream-dotnet-client#299]
### Describe the bug

I was planning to play with new filters features. I deployed the beta release 
![image](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/assets/11612804/44b103e9-ab60-481e-b0fb-f00dc738b4ed)

I configured my consumer:
```csharp
ConsumerFilter = new ConsumerFilter()
{
    PostFilter = (m) =>
    {
        return branchFilter.Contains((string)m.ApplicationProperties["routing-key"]);
    },
    Values = branchFilter
},
```

I get the following error
```
System.AggregateException: One or more errors occurred. (Broker does not support filtering. You need RabbitMQ 3.13.0 or later.)
 ---> RabbitMQ.Stream.Client.UnsupportedOperationException: Broker does not support filtering. You need RabbitMQ 3.13.0 or later.
   at RabbitMQ.Stream.Client.RawConsumerConfig.Validate() in /_/RabbitMQ.Stream.Client/RawConsumer.cs:line 85
   at RabbitMQ.Stream.Client.RawConsumer.Init() in /_/RabbitMQ.Stream.Client/RawConsumer.cs:line 409
   at RabbitMQ.Stream.Client.RawConsumer.Create(ClientParameters clientParameters, RawConsumerConfig config, StreamInfo metaStreamInfo, ILogger logger) in /_/RabbitMQ.Stream.Client/RawConsumer.cs:line 188
   at RabbitMQ.Stream.Client.RawSuperStreamConsumer.InitConsumer(String stream) in /_/RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs:line 159
   at RabbitMQ.Stream.Client.RawSuperStreamConsumer.GetConsumer(String stream) in /_/RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs:line 171
   at RabbitMQ.Stream.Client.RawSuperStreamConsumer.StartConsumers() in /_/RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs:line 182
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at RabbitMQ.Stream.Client.RawSuperStreamConsumer..ctor(RawSuperStreamConsumerConfig config, IDictionary`2 streamInfos, ClientParameters clientParameters, ILogger logger) in /_/RabbitMQ.Stream.Client/RawSuperStreamConsumer.cs:line 57
   at RabbitMQ.Stream.Client.StreamSystem.CreateSuperStreamConsumer(RawSuperStreamConsumerConfig rawSuperStreamConsumerConfig, ILogger logger) in /_/RabbitMQ.Stream.Client/StreamSystem.cs:line 224
```

### Reproduction steps

1. Deploy new beta rabbitmq version
2. Use client version 1.7.0
3. Use filters

### Expected behavior

It should be possible to connect to beta rabbitmq with 1.7.0 client

**Comment by Gsantomaggio** [comment]
That's odd since all the [filter tests](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/Tests/FilterTest.cs#L137-L157) use the the [ci](3.13.0-beta-6; see https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/.github/workflows/build-test.yaml#L46)

Please let me know if the client is connected to the correct server. 


btw I tested with:
```
 docker run -it --rm --name rabbitmq-stream-client-test \
                -p 5552:5552 -p 5672:5672 -p 15672:15672 \
                -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_stream advertised_host localhost" \
                --pull always \
                rabbitmq:3.13.0-beta.6-management
```

Then:
```
docker exec rabbitmq-stream-client-test   rabbitmq-plugins enable rabbitmq_stream_management 
```


![Screenshot 2023-09-14 at 21 44 08](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/assets/386987/97349561-5b92-49fb-91e8-1f3b76b0d67f)


```csharp
var loggerFactory = LoggerFactory.Create(builder =>
{
    builder.AddSimpleConsole();
    builder.AddFilter("RabbitMQ.Stream", LogLevel.Debug);
});

var logger = loggerFactory.CreateLogger<Consumer>();
var streamLogger = loggerFactory.CreateLogger<StreamSystem>();

var config = new StreamSystemConfig();
var system = await StreamSystem.Create(config, streamLogger).ConfigureAwait(false);
string streamName = "test-stream";
await system.CreateStream(new StreamSpec(streamName)).ConfigureAwait(false);

var consumedMessages = 0;
var consumer = await Consumer.Create(new ConsumerConfig(system, streamName)
{
    OffsetSpec = new OffsetTypeFirst(),

    // This is mandatory for enabling the filter
    Filter = new ConsumerFilter()
    {
        Values = new List<string>() {"Alabama"}, // <1>
        PostFilter = message => message.ApplicationProperties["state"].Equals("Alabama"), // <2>
        MatchUnfiltered = true
    },
    MessageHandler = (_, _, _, message) =>
    {
        logger.LogInformation("Received message with state {State} - consumed {Consumed}",
            message.ApplicationProperties["state"], ++consumedMessages);
        return Task.CompletedTask;
    }
},logger).ConfigureAwait(false);

await Task.Delay(10_000).ConfigureAwait(false);
await consumer.Close().ConfigureAwait(false);
await system.Close().ConfigureAwait(false);
```

Can you please try the above steps?

**Comment by aeb-dev** [comment]
the pod contains the following image: `image: docker.io/rabbitmq:3.13-rc-management`

This is a local kind deployment there is no other rabbitmq

I will try the code

**Comment by aeb-dev** [comment]
I am getting the same error with your code.
```
RabbitMQ.Stream.Client.UnsupportedOperationException: Broker does not support filtering. You need RabbitMQ 3.13.0 or later.
   at RabbitMQ.Stream.Client.RawConsumerConfig.Validate() in /_/RabbitMQ.Stream.Client/RawConsumer.cs:line 85
   at RabbitMQ.Stream.Client.RawConsumer.Init() in /_/RabbitMQ.Stream.Client/RawConsumer.cs:line 409
   at RabbitMQ.Stream.Client.RawConsumer.Create(ClientParameters clientParameters, RawConsumerConfig config, StreamInfo metaStreamInfo, ILogger logger) in /_/RabbitMQ.Stream.Client/RawConsumer.cs:line 188
   at RabbitMQ.Stream.Client.StreamSystem.CreateRawConsumer(RawConsumerConfig rawConsumerConfig, ILogger logger) in /_/RabbitMQ.Stream.Client/StreamSystem.cs:line 367
   at RabbitMQ.Stream.Client.Reliable.ConsumerFactory.StandardConsumer(Boolean boot) in /_/RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs:line 45
   at RabbitMQ.Stream.Client.Reliable.ConsumerFactory.CreateConsumer(Boolean boot) in /_/RabbitMQ.Stream.Client/Reliable/ConsumerFactory.cs:line 32
   at RabbitMQ.Stream.Client.Reliable.Consumer.CreateNewEntity(Boolean boot) in /_/RabbitMQ.Stream.Client/Reliable/Consumer.cs:line 183
   at RabbitMQ.Stream.Client.Reliable.ReliableBase.Init(Boolean boot, IReconnectStrategy reconnectStrategy) in /_/RabbitMQ.Stream.Client/Reliable/ReliableBase.cs:line 65
   at RabbitMQ.Stream.Client.Reliable.ReliableBase.Init(IReconnectStrategy reconnectStrategy) in /_/RabbitMQ.Stream.Client/Reliable/ReliableBase.cs:line 48
   at RabbitMQ.Stream.Client.Reliable.Consumer.Create(ConsumerConfig consumerConfig, ILogger`1 logger) in /_/RabbitMQ.Stream.Client/Reliable/Consumer.cs:line 174
```

I am sure I am using the correct rabbitmq because when I don't use consumer filter I am seeing the changes on management

**Comment by aeb-dev** [comment]
I am using the following config:
```csharp
var ss = await StreamSystem.Create(
    new StreamSystemConfig()
    {
        AddressResolver = new AddressResolver(new DnsEndPoint("localhost", 30552)),
        Endpoints = new List<EndPoint> { new DnsEndPoint("localhost", 30552) },
        UserName = "test",
        Password = "test",
        VirtualHost = "test"
    }
);
```

**Comment by aeb-dev** [comment]
I tried docker commands and it works as expect for both `rabbitmq:3.13-rc-management` and `rabbitmq:3.13.0-beta.6-management`

I don't have any idea how deploying to kind can effect this

**Comment by aeb-dev** [comment]
cluster.yaml:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.24.15
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 31672
        hostPort: 31672
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 30672
        hostPort: 30672
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 30552
        hostPort: 30552
        listenAddress: "127.0.0.1"
        protocol: TCP
```

values.yaml
```yaml
global:
  storageClass: standard

clusterOperator:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 800Mi
    requests:
      cpu: 100m
      memory: 250Mi
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true

msgTopologyOperator:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 800Mi
    requests:
      cpu: 100m
      memory: 250Mi
  metrics:
    enabled: false
    serviceMonitor:
      enabled: true
```

rabbitmq.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-rabbitmq-creds
stringData:
  password: test
  username: test
type: Opaque
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: test.classic-test.fanout
spec:
  destination: test.classic
  destinationType: queue
  rabbitmqClusterReference:
    name: main-rabbitmq
  source: test.fanout
  vhost: test
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: test.stream-test.fanout
spec:
  destination: test.stream
  destinationType: queue
  rabbitmqClusterReference:
    name: main-rabbitmq
  source: test.fanout
  vhost: test
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: test.fanout
spec:
  autoDelete: false
  durable: true
  name: test.fanout
  rabbitmqClusterReference:
    name: main-rabbitmq
  type: fanout
  vhost: test
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: test
spec:
  permissions:
    configure: .*
    read: .*
    write: .*
  rabbitmqClusterReference:
    name: main-rabbitmq
  user: test
  vhost: test
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: test.classic
spec:
  durable: false
  name: test.classic
  rabbitmqClusterReference:
    name: main-rabbitmq
  type: classic
  vhost: test
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: test.stream
spec:
  arguments:
    x-queue-leader-locator: least-leaders
    x-queue-type: stream
  durable: true
  name: test.stream
  rabbitmqClusterReference:
    name: main-rabbitmq
  type: stream
  vhost: test
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: main-rabbitmq
spec:
  image: docker.io/rabbitmq:3.13-rc-management
  override:
    service:
      spec:
        ports:
        - name: management
          nodePort: 31672
          port: 15672
        - name: amqp
          nodePort: 30672
          port: 5672
        - name: stream
          nodePort: 30552
          port: 5552
          protocol: TCP
          targetPort: stream
        type: NodePort
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              ports:
              - containerPort: 5552
                name: stream
                protocol: TCP
  persistence:
    storage: 2Gi
    storageClassName: standard
  rabbitmq:
    additionalPlugins:
    - rabbitmq_consistent_hash_exchange
    - rabbitmq_management
    - rabbitmq_management_agent
    - rabbitmq_stream
    - rabbitmq_stream_management
    - rabbitmq_federation
    - rabbitmq_federation_management
    - rabbitmq_mqtt
    - rabbitmq_web_mqtt
    - rabbitmq_web_dispatch
    - rabbitmq_peer_discovery_k8s
    - rabbitmq_peer_discovery_common
    - rabbitmq_prometheus
    - rabbitmq_shovel
    - rabbitmq_shovel_management
    - rabbitmq_random_exchange
  replicas: 1
  resources: {}
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: test
spec:
  importCredentialsSecret:
    name: test-rabbitmq-creds
  rabbitmqClusterReference:
    name: main-rabbitmq
  tags:
  - administrator
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: test
spec:
  name: test
  rabbitmqClusterReference:
    name: main-rabbitmq
```

https://kind.sigs.k8s.io/docs/user/quick-start/ and then run the following commands

```
kind create cluster --config=cluster.yaml
kubectl config use-context kind-kind
helm upgrade --install rabbitmq-cluster-operator oci://registry-1.docker.io/bitnamicharts/rabbitmq-cluster-operator -f ./values.yaml
kubectl apply -k ./rabbitmq.yaml
```

Then you can use [this config](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/299#issuecomment-1720141183) to connect to rabbitmq

**Comment by Gsantomaggio** [comment]
@aeb-dev thank you for the detailed info.
Do you have a chance to test https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/301 it adds more debug information to understand what's going on.

Please enable the log in debug mode. 
Thank you

**Comment by aeb-dev** [comment]
The problem is solved as explained [here](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/301)
