### ISSUE TITLE
ConsumerShouldReceiveDelivery_MultipleMessages bug

### ISSUE THREAD

**Issue by CasperTDK** [rabbitmq/rabbitmq-stream-dotnet-client#5]
There seems to be an issue with span calculation for multiple messages with content.

I have written a test to confirm the issue

**Comment by CasperTDK** [comment]
Test output:

```
System.ArgumentOutOfRangeException
Specified argument was out of the range of valid values. (Parameter 'length')
   at System.ThrowHelper.ThrowStartOrEndArgumentValidationException(Int64 start)
   at System.Buffers.ReadOnlySequence`1.Slice(Int64 start, Int64 length)
   at RabbitMQ.Stream.Client.Deliver.get_Messages()+MoveNext() in C:\projects\rabbitmq-stream-dotnet-client\RabbitMQ.Stream.Client\Deliver.cs:line 34
   at Tests.ClientTests.ConsumerShouldReceiveDelivery_MultipleMessages() in C:\projects\rabbitmq-stream-dotnet-client\Tests\ClientTests.cs:line 219
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__1(Object _) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\AsyncTestSyncContext.cs:line 75

Received msg: hi0
```

**Comment by CasperTDK** [comment]
Hi @acogoluegnes 

Do you also have a clue here?
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/RabbitMQ.Stream.Client/Deliver.cs

`Chunk.Read` looks correct to me

**Comment by CasperTDK** [comment]
@kjnilsson I should note that it does NOT fail if the message payload is empty

**Comment by CasperTDK** [comment]
Solved in main
